export default [
    "mermen, too",
    "morn emote",
    "mono-meter",
    "moon meter",
    "moron meet",
    "roe moment",
    "memo tenor",
    "memo toner",
    "metro omen",
    "emote on, mr.",
    "emote, mr.?! no!",
    "no mere tom",
    "or teen mom",
    "ere mom not",
    "mom on tree",
    "moon mr tee",
    "not more me!",
    "me on metro",
    "to more men!",
    "mr. toe omen",
    "met no more",
    "one tome, mr",
    "one to me, mr."
];